// This var holds all the config file data
var df_config;

function bool2int(someBool) {
	return someBool ? 1 : 0;
};

$("#selectAll").click( function() {
	$("#configOutput").select();
});

$("#generate").click( function() {

	df_config = ''

	df_config += '//Special Thanks To Hades For Help In Design Of The Base Configuration.';
	df_config += '\necho "^7=========================================================="';
	df_config += '\necho "^7===^2File Generated By Newbrict\'s Configuration Generator^7==="';
	df_config += '\necho "^7===^2             http://www.dimit.me/dfcfg/             ^7==="';
	df_config += '\necho "^7===^1         Base Script Last Updated 2015-08-30        ^7==="';
	df_config += '\necho "^7===^1            Thanks for all your support:            ^7==="';
	df_config += '\necho "^7===^1 RaaCK, Mucki, Inder, Hades, Spanx, Hunnybunny, GPL ^7==="';
	df_config += '\necho "^7===^1     Suggestions/Bugs/Etc --> Newbrict@gmail.com    ^7==="';
	df_config += '\necho "^7=========================================================="';

	// Graphics Settings

	df_config += '\n\n//GRAPHICS SETTINGS'

	var wantsCustomResolution = $("#r_mode").is(':checked');

	if(wantsCustomResolution) {

		df_config += '\nseta r_mode "-1"';

		var r_customwidth = $("#r_customwidth").val();
		df_config += `\nseta r_customwidth "${r_customwidth}"`;

		var r_customheight = $("#r_customheight").val();
		df_config += `\nseta r_customheight "${r_customheight}"`;
	}

	var r_fullscreen = bool2int($("#r_fullscreen").is(':checked'));
	df_config += `\nseta r_fullscreen "${r_fullscreen}"`;

	var r_fastsky = bool2int($("#r_fastsky").is(':checked'));
	df_config += `\nseta r_fastsky "${r_fastsky}"`;

	var r_fullbright = bool2int($("#r_fullbright").is(':checked'));
	df_config += `\nseta r_fullbright "${r_fullbright}"`;

	df_config += '\nseta r_finish "1"';

	var r_picmip = $("#r_picmip").val();
	df_config += `\nseta r_picmip "${r_picmip}"`;


	//MOUSE SETTINGS

	df_config += '\n\n//MOUSE SETTINGS';

	var in_mouse = $("#in_mouse").val();
	df_config += `\nseta in_mouse "${in_mouse}"`;

	var sensitivity = $("#sensitivity").val();
	df_config += `\nseta sensitivity "${sensitivity}"`;

	df_config += '\nseta m_forward ".25"';
	df_config += '\nseta m_side ".025"';
	df_config += '\nseta m_filter "0"';

	var wantsMouseAcceleration = $("#cl_mouseaccel").is(':checked');
	if(wantsMouseAcceleration) {
		df_config += '\nseta cl_mouseAccel "1"';
	}

	//GAME SETTINGS

	df_config += '\n\n//GAME SETTINGS';
	var df_mp_nodrawradius = $("#df_mp_nodrawradius").val();
	df_config += `\nseta df_mp_nodrawradius "${df_mp_nodrawradius}"`;

	var cg_zoomfov = $("#cg_zoomfov").val();
	df_config += `\nseta cg_zoomfov "${cg_zoomfov}"`;

	var cg_fov = $("#cg_fov").val();
	df_config += `\nseta cg_fov "${cg_fov}"`;

	df_config += '\nseta cg_bobup "0"';
	df_config += '\nseta cg_bobpitch "0"';
	df_config += '\nseta cg_bobroll "0"';

	//HUD SETTINGS

	df_config += '\n\n//HUD SETTINGS';

	var cg_crosshairsize = $("#cg_crosshairsize").val();
	df_config += `\nseta cg_crosshairSize "${cg_crosshairsize}"`;

	var df_hud_cgaz = $("#df_hud_cgaz").val();
	df_config += `\nseta df_hud_cgaz "${df_hud_cgaz}"`;

	var df_hud_cgaz_ypos = $("#df_hud_cgaz_ypos").val();
	df_config += `\nseta df_hud_cgaz_ypos "${df_hud_cgaz_ypos}"`;

	var df_name = $("#df_name").val();
	df_config += `\nseta df_name "${df_name}"`;

	df_config += '\nseta df_hud_color "8"';

	var df_chs_draw = new Array(3);
	df_chs_draw[0] = $("#df_chs0_draw").is(":checked");
	df_chs_draw[1] = $("#df_chs1_draw").is(":checked");
	df_chs_draw[2] = $("#df_chs2_draw").is(":checked");

	if( df_chs_draw[0] ) {
		df_config += `\nseta df_chs0_draw "${bool2int(df_chs0_draw)}"`;
	}

	if( df_chs_draw[1] ) {
		df_config += `\nseta df_chs1_draw "${bool2int(df_chs1_draw)}"`;
		for( var i = 1; i != 9; ++i ) {
			var df_chs1_draw_infoi = $("#df_chs1_info"+i).val();
			if(df_chs1_draw_infoi != "") {
				df_config += `\nseta df_chs1_draw${i} "${df_chs1_draw_infoi}"`;
			}
		}
	}

	if( df_chs_draw[2] ) {
		df_config += `\nseta df_chs2_draw "${bool2int(df_chs2_draw)}"`;
		for( var i = 1; i != 9; ++i ) {
			var df_chs2_draw_infoi = $("#df_chs2_info"+i).val();
			if(df_chs2_draw_infoi != "") {
				df_config += `\nseta df_chs2_draw${i} "${df_chs2_draw_infoi}"`;
			}
		}
	}


	var df_chs2_offsety = $("#df_chs2_offsety").val();
	df_config += `\nseta df_chs2_OffsetY "${df_chs2_offsety}"`;

	var df_chs2_offsetx = $("#df_chs2_offsetx").val();
	df_config += `\nseta df_chs2_OffsetX "${df_chs2_offsetx}"`;

	var df_chs2_fontsize = $("#df_chs2_fontsize").val();
	df_config += `\nseta df_chs2_FontSize "${df_chs2_fontsize}"`;

	var df_chs1_fonttransparency = $("#df_chs1_fonttransparency").val();
	df_config += `\nseta df_chs1_FontTransparency "${df_chs1_fonttransparency}"`;

	var df_chs1_fontsize = $("#df_chs1_fontsize").val();
	df_config += `\nseta df_chs1_FontSize "${df_chs1_fontsize}"`;

	var wantsDrawTimer = $("#cg_drawtimer").is(':checked');
	if( wantsDrawTimer ) {
		df_config += '\nseta cg_drawtimer "1"';
	}

	var wantsDrawFPS = $("#cg_drawfps").is(':checked');
	if( wantsDrawFPS ) {
		df_config += '\nseta cg_drawfps "1"';
	}

	//NETWORK SETTINGS

	df_config += '\n\n//NETWORK SETTINGS';

	var rate = $("#rate").val();
	df_config += `\nseta rate "${rate}"`;

	var snaps = $("#snaps").val();
	df_config += `\nseta snaps "${snaps}"`;

	var cl_packetdup = $("#cl_packetdup").val();
	df_config += `\nseta cl_packetdup "${cl_packetdup}"`;

	var cl_maxpackets = $("#cl_maxpackets").val();
	df_config += `\nseta cl_maxpackets "${cl_maxpackets}"`;

	//DFWC RULESET

	df_config += '\n\n//DFWC RULESET';

	df_config += '\nseta timescale "1"';
	df_config += '\nseta g_synchronousClients "1"';
	df_config += '\nseta pmove_fixed "0"';
	df_config += '\nseta pmove_msec "8"';
	df_config += '\nseta com_maxfps "125"';
	df_config += '\nseta g_speed "320"';
	df_config += '\nseta g_gravity "800"';
	df_config += '\nseta g_knockback "1000"';
	df_config += '\nseta sv_cheats "0"';
	df_config += '\nseta handicap "100"';

	//FILL THE MODAL OUTPUT
	$("#configOutput").val(df_config);
});
