<?php
//graphics
$r_fullscreen = $_POST['r_fullscreen']=="on"?1:0;
$r_fastsky = $_POST['r_fastsky']=="on"?1:0;
$r_fullbright = $_POST['r_fullbright']=="on"?1:0;
$r_picmip = $_POST['r_picmip'];
$r_mode = $_POST['r_mode']=="on"?-1:3;
$r_customheight = $_POST['r_customheight'];
$r_customwidth = $_POST['r_customwidth'];

//mouse
$in_mouse = $_POST['in_mouse'];
$sensitivity = $_POST['sensitivity'];
$cl_mouseaccel = $_POST['cl_mouseaccel']=="on"?1:0;

//game
$cg_fov = $_POST['cg_fov'];
$cg_zoomfov = $_POST['cg_zoomfov'];
$df_mp_nodrawradius = $_POST['df_mp_nodrawradius'];
$cg_bob = $_POST['cg_bob'];

//hud
$cg_drawtimer = $_POST['cg_drawtimer']=="on"?1:0;
$cg_drawfps = $_POST['cg_drawfps']=="on"?1:0;
$cg_drawcrosshair = $_POST['cg_drawcrosshair'];
$cg_crosshairsize = $_POST['cg_crosshairsize'];
$df_hud_cgaz = $_POST['df_hud_cgaz'];
$df_hud_cgaz_ypos = $_POST['df_hud_cgaz_ypos'];

$df_chs0_draw = $_POST['df_chs0_draw']=="on"?1:0;
$df_chs1_draw = $_POST['df_chs1_draw']=="on"?1:0;
$df_chs2_draw = $_POST['df_chs2_draw']=="on"?1:0;

$df_chs1_fontsize = $_POST['df_chs1_fontsize'];
$df_chs1_fonttransparency = $_POST['df_chs1_fonttransparency'];
$df_chs1_info = array();
$df_chs1_info[1] = $_POST['df_chs1_info1'];
$df_chs1_info[2] = $_POST['df_chs1_info2'];
$df_chs1_info[3] = $_POST['df_chs1_info3'];
$df_chs1_info[4] = $_POST['df_chs1_info4'];
$df_chs1_info[5] = $_POST['df_chs1_info5'];
$df_chs1_info[6] = $_POST['df_chs1_info6'];
$df_chs1_info[7] = $_POST['df_chs1_info7'];
$df_chs1_info[8] = $_POST['df_chs1_info8'];

$df_chs2_fontsize = $_POST['df_chs2_fontsize'];
$df_chs2_offsetx = $_POST['df_chs2_offsetx'];
$df_chs2_offsety = $_POST['df_chs2_offsety'];
$df_chs2_info = array();
$df_chs2_info[1] = $_POST['df_chs2_info1'];
$df_chs2_info[2] = $_POST['df_chs2_info2'];
$df_chs2_info[3] = $_POST['df_chs2_info3'];
$df_chs2_info[4] = $_POST['df_chs2_info4'];
$df_chs2_info[5] = $_POST['df_chs2_info5'];
$df_chs2_info[6] = $_POST['df_chs2_info6'];
$df_chs2_info[7] = $_POST['df_chs2_info7'];
$df_chs2_info[8] = $_POST['df_chs2_info8'];

//network
$rate = $_POST['rate'];
$snaps = $_POST['snaps'];
$cl_maxpackets = $_POST['cl_maxpackets'];
$cl_packetdup = $_POST['cl_packetdup'];

//misc
$df_name = $_POST['df_name'];

$TestText = fopen( "cfgs/".$df_name.".cfg","w");
fwrite($TestText, '
//Special Thanks To Hades For Help In Design Of The Base Configuration.
echo "^7=========================================================="
echo "^7===^2File Generated By Newbrict\'s Configuration Generator^7==="
echo "^7===^2              http://www.newbrict.com/              ^7==="
echo "^7===^1         Base Script Last Updated 2013-10-05        ^7==="
echo "^7===^1            Thanks for all your support:            ^7==="
echo "^7===^1 RaaCK, Mucki, Inder, Hades, Spanx, Hunnybunny  :)  ^7==="
echo "^7===^1     Suggestions/Bugs/Etc --> Newbrict@gmail.com    ^7==="
echo "^7=========================================================="

//GRAPHICS SETTINGS');
if($r_mode==-1) {
fwrite($TestText, '
seta r_mode "-1"
seta r_customwidth "'.$r_customwidth.'"
seta r_customheight "'.$r_customheight.'"');
}

fwrite($TestText, '
seta r_fullscreen "'.$r_fullscreen.'"
seta r_fastsky "'.$r_fastsky.'"
seta r_fullbright "'.$r_fullbright.'"
seta r_finish "1"
seta r_picmip "'.$r_picmip.'"

//MOUSE SETTINGS
seta in_mouse "'.$in_mouse.'"
seta sensitivity "'.$sensitivity.'"
seta m_forward ".25"
seta m_side ".025"
seta m_filter "0"');

if($cl_mouseaccel==1) {
fwrite($TestText, '
seta cl_mouseAccel "1"');
}

fwrite($TestText, '
//GAME SETTINGS
seta df_mp_nodrawradius "'.$df_mp_nodrawradius.'"
seta cg_zoomfov "'.$cg_zoomfov.'"
seta cg_fov "'.$cg_fov.'"');

if($cg_bob=="on") {
fwrite($TestText, '
seta cg_bobup "0"
seta cg_bobpitch "0"
seta cg_bobroll "0"');
}

fwrite($TestText, '
//HUD SETTINGS
seta cg_crosshairSize "'.$cg_crosshairsize.'"
seta df_hud_cgaz "'.$df_hud_cgaz.'"
seta df_hud_cgaz_ypos "'.$df_hud_cgaz_ypos.'"
seta df_name "'.$df_name.'"
seta df_hud_color "8"
seta df_chs2_Draw "'.$df_chs2_draw.'"
seta df_chs1_Draw "'.$df_chs1_draw.'"
seta df_chs0_Draw "'.$df_chs0_draw.'" ');

for($i=1;$i<9;++$i){
  if($df_chs2_info[$i] != ""){
  fwrite($TestText, '
df_chs2_info'.$i.' "'.$df_chs2_info[$i].'"');
  }
}

for($i=1;$i<9;++$i){
  if($df_chs1_info[$i] != ""){
  fwrite($TestText, '
df_chs1_info'.$i.' "'.$df_chs1_info[$i].'"');
  }
}

fwrite($TestText, '
seta df_chs2_OffsetY "'.$df_chs2_offsety.'"
seta df_chs2_OffsetX "'.$df_chs2_offsetx.'"
seta df_chs2_FontSize "'.$df_chs2_fontsize.'"

seta df_chs1_FontTransparency "'.$df_chs1_fonttransparency.'"
seta df_chs1_FontSize "'.$df_chs1_fontsize.'"');

if($cg_drawtimer==1) {
fwrite($TestText, '
seta cg_drawtimer "1"');
}

if($cg_drawfps==1) {
fwrite($TestText, '
seta cg_drawfps "1"');
}

fwrite($TestText, '
//NETWORK SETTINGS
seta rate "'.$rate.'"
seta snaps "'.$snaps.'"
seta cl_packetdup "'.$cl_packetdup.'"
seta cl_maxpackets "'.$cl_maxpackets.'"

//OFFLINE SETTINGS
seta timescale               "1"
seta g_synchronousClients    "1"
seta pmove_fixed             "0"
seta pmove_msec              "8"
seta com_maxfps              "125"
seta g_speed                 "320"
seta g_gravity               "800"
seta g_knockback             "1000"
seta sv_cheats               "0"
seta handicap                "100"

');
fclose($TestText);
$file_path="cfgs/".$df_name.".cfg";
header( 'Location: '.$file_path ) ;
?>
